# GCP dynamic inventory configuration
plugin: gcp_compute
projects:
  - your-gcp-project-id # Replace with your GCP project ID
auth_kind: serviceaccount
service_account_file: /path/to/your/gcp-sa-key.json # Replace with the path to your GCP service account key
keyed_groups:
  - key: labels
    prefix: gcp_
  - key: zone
    prefix: gcp_zone_
filters:
  - machineType = "e2-medium"
  - name = "commenttest-app-instance"
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
